apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloping2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloping2
  template:
    metadata:
      labels:
        app: helloping2
    spec:
      containers:
        - image: cqueirolo/helloping2:latest
          name: helloping2
          ports:
          - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: helloping2
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP
  ports:
    - name: helloping2
      port: 8080
      targetPort: 8080
  selector:
    app: helloping2